/* Program - Reverse a string using Stack@Treesa Jose
Completed on: 26-07-2025 */

#include <stdio.h>
#define SIZE 15

void push(char str[], int *top, char ch) {
    if (*top == SIZE - 1) {
        printf("Error: Stack is full\n");
    } else {
        str[++(*top)] = ch;
    }
}

char pop(char str[], int *top) {
    if (*top == -1) {
        printf("Error: Stack is empty\n");
        return '\0';
    } else {
        return str[(*top)--];
    }
}

int menu() {
    int ch;
    printf("\nMENU\n1. Enter String\n2. Reverse String using Stack\n");
    printf("3. Display Original and Reversed String\n4. Exit\nEnter your choice: ");
    scanf("%d", &ch);
    return ch;
}

void reverseStringUsingStack() {
    char str[SIZE], rev[SIZE];
    int top;
    int ch, i, len = 0;

    while ((ch = menu()) != 4) {
        getchar(); // Consume newline generated by menu()

        switch (ch) {
            case 1:
                printf("Enter a string: ");
                fgets(str, SIZE, stdin);

                // Manually calculate length and remove newline
                len = 0;
                for (i = 0; i < SIZE; i++) {
                    if (str[i] == '\n' || str[i] == '\0') {
                        str[i] = '\0';
                        break;
                    }
                    len++;
                }
                break;

            case 2:
                top = -1;

                // Push characters to stack
                for (i = 0; i < len; i++) {
                    push(str, &top, str[i]);
                }

                // Pop characters into rev
                for (i = 0; i < len; i++) {
                    rev[i] = pop(str, &top);
                }
                rev[len] = '\0';
                printf("String reversed successfully.\n");
                break;

            case 3:
                printf("Original String: %s\n", str);
                printf("Reversed String: %s\n", rev);
                break;

            default:
                printf("Invalid choice. Try again.\n");
        }
    }
}

int main() {
    reverseStringUsingStack();
    return 0;
}

